sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kmanago/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kmanago/docker-react npm run test -- ---coverage
