sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kmanago/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kmanago/docker-react npm run test -- ---coverage

  deploy: 
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "Docker-env"
    bucket-name: "elasticbeanstalk-us-east-1-151839958244"
    bucket-path: "docker-react"
    on:
        branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
      secure: "$AWS_SECRET_KEY"